name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Please remember to link this issue to a project and add information regarding tasks and progress if not already completed.

          pullRequestOpened: |
            👋 @{{ author }}
            Please remember to link this pull request to an issue if not already completed.
            **Before merging, wait for SonarCloud to complete a scan.** It may not show up initially in tests, a comment will appear when the scan is completed.
